/*11. Write a C program (we'll refer to it as A) that creates a child process B. Process B generates one random number N between 100 and 1000. Process A keeps generating and sending random numbers between 50 and 1050 to B until the absolute difference between the number generated by A and the number generated by B is less than 50. B prints the generated numbers and all the received numbers. A will print at the end the number of numbers generated until the stop condition was met.
Example:
Process B has generated 433
B received 244; difference: 189
B received 367; difference: 66
B received 723; difference: 290
B received 465; difference: 32
Process A has generated 4 numbers
*/

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>

int main(int argc, char** argv)
{
	int a2b[2],b2a[2];
	pipe(a2b); pipe(b2a);
	int pid = fork();
	if(pid == -1)
	{
		perror("Error on fork");
		exit(1);
	}
	if(pid == 0)
	{
		//Process B
		srand(time(0));
		close(a2b[1]); close(b2a[0]);
		int n = rand()%901 + 100;
		printf("Process B has generated %d\n", n);
		while(1)
		{	
			int x, stop = 1;
			if(read(a2b[0],&x,sizeof(int))<0)
				perror("Error on read");
			printf("B received %d; difference: %d\n", x, abs(n-x));
			if(abs(n-x) <= 50)
			{
				if(write(b2a[1], &stop, sizeof(int))<0)
					perror("Error on write");
				break;
			}
			stop = 0;
			if(write(b2a[1], &stop, sizeof(int))<0)
				perror("Error on write");
		}
		close(a2b[0]); close(b2a[1]);
		exit(0);
	}
	//Process A
	srand(time(0)+1);
	close(a2b[0]); close(b2a[1]);
	int count = 0;
	while(1)
	{
		srand(time(0)+count);
		int x = rand()%901+50;
		count += 1;
		if(write(a2b[1], &x, sizeof(int))<0)
			perror("Error on write in A");
		int stop;
		if(read(b2a[0], &stop, sizeof(int))<0)
			perror("Error on read in A");
		if(stop == 1)
			break;
	}
	close(a2b[1]); close(b2a[0]);
	printf("A generated %d\n", count);
	return 0;
}
