package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class BothSceneController {
	@FXML
	private Button button1;
	
	@FXML
	private Button button2;

	// Event Listener on Button[#button1].onAction
	@FXML
	public void handleButtonAction(ActionEvent event) throws IOException{
		// TODO Autogenerated
		Stage stage; 
	     Parent root;
	     if(event.getSource()==button1){
	        //get reference to the button's stage         
	        stage=(Stage) button1.getScene().getWindow();
	        //load up OTHER FXML document
	        root = FXMLLoader.load(getClass().getResource("Scene2.fxml"));
	      }
	     else{
	       stage=(Stage) button2.getScene().getWindow();
	       root = FXMLLoader.load(getClass().getResource("Scene1.fxml"));
	      }
	     //create a new scene with root and set the stage
	      Scene scene = new Scene(root, 400, 400);
	      stage.setScene(scene);
	      stage.show();
	}
}
